{ self, inputs, ... }: {

  flake.nixosModules.vvhNginx = { config, lib, pkgs, ... }: {

    services = {
      cloudflare-dyndns = {
        enable = true;
        domains = [
          "rengo1136.org"
        ];
        proxied = true;
        apiTokenFile = config.age.secrets."cloudflare-ddns".path;
      };
      nginx = {
        enable = true;
        recommendedGzipSettings = true;
        recommendedOptimisation = true;
        recommendedProxySettings = true;
        recommendedTlsSettings = true;
        virtualHosts = {
          ## qbittorrent
          "bt.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:8080";
              proxyWebsockets = true;
            };
          };
          ## prowlarr
          "downs.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:9696";
              proxyWebsockets = true;
            };
          };
          ## radarr
          "film.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:7878";
              proxyWebsockets = true;
            };
          };
          ## jellyfin
          "medusa.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:8096";
              proxyWebsockets = true;
            };
          };
          ## lidarr
          "music.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:8686";
              proxyWebsockets = true;
            };
          };
          ## navidrome
          "play.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:4533";
              proxyWebsockets = true;
            };
          };
          ## subtitles
          "subs.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:6767";
              proxyWebsockets = true;
            };
          };
          ## sonarr
          "tv.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.4:8989";
              proxyWebsockets = true;
            };
          };
        };
      };
    };

    # Give Nginx permission to read the certificates generated by ACME
    users.users.nginx.extraGroups = [ "acme" ];
    
    security.acme = {
      acceptTerms = true;
      defaults.email = "valentinvergara@gmail.com";
      certs = {
        "rengo1136.org" = {
          domain = "*.rengo1136.org";
          dnsProvider = "cloudflare";
          environmentFile = config.age.secrets."cloudflare-acme".path;
        };
      };
    };
  };
}
