;;; custom.el --- machine-generated by `customize', see init.el -*- lexical-binding: t; -*-

;; Deliberately left with just the face tweaks carried over from Doom's
;; custom.el. `package-selected-packages' was dropped: package.el is
;; disabled (see early-init.el), packages come from Nix instead, so that
;; variable has nothing to do here anymore.
(custom-set-faces
 '(font-lock-comment-face ((t (:slant italic))))
 '(font-lock-keyword-face ((t (:slant italic :weight bold)))))
