{ self, inputs, ... }: {

  flake.nixosModules.vvhNginx = { config, lib, pkgs, ... }: {

    services = {
      cloudflare-dyndns = {
        enable = true;
        domains = [
          "rengo1136.org"
        ];
        proxied = true;
        apiTokenFile = config.age.secrets."cloudflare-ddns".path;
      };
      nginx = {
        enable = true;
        recommendedGzipSettings = true;
        recommendedOptimisation = true;
        recommendedProxySettings = true;
        recommendedTlsSettings = true;
        virtualHosts = {
          "npm.rengo1136.org" = {
            forceSSL = true;
            useACMEHost = "rengo1136.org";
            locations."/" = {
              proxyPass = "http://10.27.115.3:81";
              proxyWebsockets = true;
            };
          };
        };
      };
    };

    # Give Nginx permission to read the certificates generated by ACME
    users.users.nginx.extraGroups = [ "acme" ];
    
    security.acme = {
      acceptTerms = true;
      defaults.email = "valentinvergara@gmail.com";
      certs = {
        "rengo1136.org" = {
          domain = "*.rengo1136.org";
          dnsProvider = "cloudflare";
          environmentFile = config.age.secrets."cloudflare-acme".path;
        };
      };
    };
  };
}
